# Generated by Django 3.0.8 on 2020-07-19 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0002_auto_20200719_0756'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Quiz',
        ),
    ]
