# Generated by Django 3.0.8 on 2020-07-20 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0006_quiz_completed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quizquestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quizId', models.IntegerField()),
                ('quizQuestiontext', models.CharField(max_length=250)),
                ('quizAnswer', models.CharField(max_length=250)),
            ],
        ),
    ]
