# Generated by Django 3.0.8 on 2020-07-21 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0007_quizquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizquestion',
            name='quizResponses',
            field=models.CharField(default='None', max_length=50),
        ),
    ]
