# Generated by Django 3.0.8 on 2020-07-21 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0008_quizquestion_quizresponses'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quizanswers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quizId', models.IntegerField()),
                ('questionId', models.IntegerField()),
                ('qAnswer', models.CharField(max_length=120)),
            ],
        ),
    ]
