# Generated by Django 3.0.8 on 2020-07-21 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0009_quizanswers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Quizanswers',
            new_name='Quizanswer',
        ),
    ]
