# Generated by Django 3.0.8 on 2020-08-03 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0011_auto_20200803_1910'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Quizcats',
            new_name='Quizcat',
        ),
    ]
